------------------------------------------
-------------- TABLES MODEL --------------
------------------------------------------

CREATE TABLE CUSTOMERS (
	CUSTOMERID INTEGER PRIMARY KEY,
	FIRSTNAME VARCHAR(250),
	LASTNAME VARCHAR(250),
	EMAIL VARCHAR(250),
	JOINDATE DATE
);

CREATE INDEX IDX_CUSTOMERS_NAME_LASTNAME ON CUSTOMERS (FIRSTNAME, LASTNAME);


CREATE TABLE ORDERS (
	ORDERID INTEGER PRIMARY KEY,
	CUSTOMERID INTEGER REFERENCES CUSTOMERS(CUSTOMERID) ON DELETE RESTRICT,
	ORDERDATE DATE,
	TOTALAMOUNT DECIMAL(20,2)
);

CREATE INDEX IDX_ORDERS_ORDERDATE ON ORDERS (ORDERDATE);


CREATE TABLE ORDERDETAILS (
	ORDERDETAILID INTEGER PRIMARY KEY,
	ORDERID INTEGER REFERENCES ORDERS(ORDERID) ON DELETE RESTRICT,
	PRODUCTID INTEGER,
	QUANTITY INTEGER,
	UNITPRICE DECIMAL(20,2)
);

CREATE INDEX IDX_ORDERDETAILS_ORDERDID ON ORDERDETAILS (ORDERID);


CREATE TABLE PRODUCTS (
	PRODUCTID INTEGER PRIMARY KEY,
	PRODUCTNAME VARCHAR(500),
	CATEGORY VARCHAR(500),
	PRICE DECIMAL(20,2)
);


--------------------------------------------------
------------- VW_CUSTOMERORDERS VIEW -------------
--------------------------------------------------

CREATE OR REPLACE VIEW VW_CUSTOMERORDERS 
AS
SELECT CUST.CUSTOMERID,
	   CUST.FIRSTNAME,
	   CUST.LASTNAME,
	   CUST.EMAIL,
	   COUNT(ORD.ORDERID) AS TOTALORDERS,
	   SUM(ORD.TOTALAMOUNT) AS TOTALAMOUNT,
	   EXTRACT(YEAR FROM JOINDATE) AS YEAR
FROM   CUSTOMERS AS CUST
LEFT JOIN ORDERS AS ORD
ON CUST.CUSTOMERID = ORD.CUSTOMERID
WHERE EXTRACT(YEAR FROM JOINDATE) = 2023
GROUP BY CUST.CUSTOMERID,
	   CUST.FIRSTNAME,
	   CUST.LASTNAME,
	   CUST.EMAIL,
	   EXTRACT(YEAR FROM JOINDATE)
;

