-----------------------------------------------------------
------------- PROCEDURE SP_MONTHLYSALESREPORT -------------
-----------------------------------------------------------

CREATE OR REPLACE PROCEDURE SP_MONTHLYSALESREPORT(
    STARTDATE DATE,
    ENDDATE DATE
)
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE NOTICE 'Ejecutando el store sp_MonthlySalesReport para el periodo: % a %', STARTDATE, ENDDATE;

    DELETE 
	FROM   MONTHLYSALESREPORT
    WHERE  ORDERDATE >= STARTDATE
    AND    ORDERDATE <= ENDDATE;

    INSERT INTO MONTHLYSALESREPORT
    SELECT
        EXTRACT(MONTH FROM ORD.ORDERDATE) AS MONTH,
		EXTRACT(YEAR FROM  ORD.ORDERDATE) AS YEAR,
		ORD.ORDERDATE,
        COUNT(DISTINCT ORD.ORDERID) AS TOTALORDER,
        SUM(DET.QUANTITY) AS TOTALQUANTITY,
        SUM(CAST(COALESCE(ORD.TOTALAMOUNT, 0) AS DECIMAL(20, 2))) AS TOTALAMOUNT
    FROM
        ORDERS AS ORD
    LEFT JOIN
        ORDERDETAILS DET ON ORD.ORDERID = DET.ORDERID  
    WHERE
        ORD.ORDERDATE >= STARTDATE
        AND ORD.ORDERDATE <= ENDDATE
    GROUP BY
        MONTH,
		YEAR,
		ORD.ORDERDATE;
END;
$$;

CREATE TABLE MONTHLYSALESREPORT
(
    MONTH INTEGER,
	YEAR INTEGER,
	ORDERDATE DATE,
    TOTALORDER INTEGER,
    TOTALQUANTITY INTEGER,
    TOTALAMOUNT NUMERIC(20,2)
);
