--------------------------------------------------
------------- VW_CUSTOMERORDERS VIEW -------------
--------------------------------------------------

CREATE VIEW VW_CUSTOMERORDERS AS
SELECT CUST.CUSTOMERID,
	   CUST.FIRSTNAME,
	   CUST.LASTNAME,
	   CUST.EMAIL,
	   COUNT(ORD.ORDERID) AS TOTALORDERS,
	   SUM(ORD.TOTALAMOUNT) AS TOTALAMOUNT,
	   EXTRACT(YEAR FROM JOINDATE) AS YEAR
FROM   CUSTOMERS CUST
LEFT JOIN ORDERS ORD
ON CUST.CUSTOMERID = ORD.CUSTOMERID
WHERE  EXTRACT(YEAR FROM JOINDATE) = 2023
GROUP BY CUST.CUSTOMERID,
	   CUST.FIRSTNAME,
	   CUST.LASTNAME,
	   CUST.EMAIL,
	   EXTRACT(YEAR FROM JOINDATE)
;


---------------------------------------------------------------
------------- MVW_CUSTOMERORDERS MATERIALIZED VIEW -------------
---------------------------------------------------------------

CREATE MATERIALIZED VIEW MVW_CUSTOMERORDERS
TABLESPACE USERS_DATA
BUILD IMMEDIATE
REFRESH FORCE
AS
SELECT CUSTOMERID,
       FIRSTNAME,
       LASTNAME,
       EMAIL,
       TOTALORDERS,
       TOTALAMOUNT,
       YEAR
FROM VW_CUSTOMERORDERS
;

CREATE INDEX IDX_MVW_CUSTOMERORDERS ON MVW_CUSTOMERORDERS (CUSTOMERID)
TABLESPACE USERS_DATA_IDX;
