---------------------------------------------------
------------- COMMON TABLE EXPRESSION -------------
---------------------------------------------------


WITH CTE_PRODUCTCATEGORY AS (
	SELECT PRO.CATEGORY,
	       YEAR(ORD.ORDERDATE) AS YEAR,
	       DET.QUANTITY,
		   DET.QUANTITY * DET.UNITPRICE AS TOTALAMOUNT
	FROM   PRODUCTS AS PRO
	INNER JOIN ORDERDETAILS AS DET
	ON     PRO.PRODUCTID = DET.PRODUCTID
	INNER JOIN ORDERS AS ORD
	ON     DET.ORDERID = ORD.ORDERID
	WHERE  YEAR(ORD.ORDERDATE) = 2023 
)
SELECT CATEGORY,
       YEAR,
	   SUM(QUANTITY) AS QUANTITY,
	   SUM(TOTALAMOUNT) AS TOTALAMOUNT
FROM   CTE_PRODUCTCATEGORY
GROUP BY CATEGORY,
       YEAR;
