------------------------------------------
-------------- TABLES MODEL --------------
------------------------------------------

CREATE TABLE CUSTOMERS (
	CUSTOMERID INT PRIMARY KEY,
	FIRSTNAME VARCHAR(200),
	LASTNAME VARCHAR(200),
	EMAIL VARCHAR(250),
	JOINDATE DATE
);
GO

CREATE INDEX IDX_CUSTOMERS_NAME ON CUSTOMERS(FIRSTNAME, LASTNAME);
GO


CREATE TABLE ORDERS (
    ORDERID INT PRIMARY KEY,
    CUSTOMERID INT,
    ORDERDATE DATE,
    TOTALAMOUNT DECIMAL(20, 2),
    FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERS(CUSTOMERID) ON DELETE CASCADE
);
GO

CREATE INDEX IDX_ORDERS_ORDERDATE ON ORDERS(ORDERDATE);
GO


CREATE TABLE ORDERDETAILS (
	ORDERDETAILID INT PRIMARY KEY,
	ORDERID INT,
	PRODUCTID INT,
	QUANTITY INT,
	UNITPRICE DECIMAL(20,2),
	FOREIGN KEY (ORDERID) REFERENCES ORDERS(ORDERID) ON DELETE CASCADE
);
GO

CREATE INDEX IDX_ORDERDETAILS_ORDERID ON ORDERDETAILS(ORDERID);
GO


CREATE TABLE PRODUCTS(
	PRODUCTID INT PRIMARY KEY,
	PRODUCTNAME VARCHAR(500),
	CATEGORY VARCHAR(250),
	PRICE DECIMAL(20,2)
);
GO
