-------------------------------------------------------------
------------- FN_ACTIVECUSTOMERS TABLE FUNCTION -------------
-------------------------------------------------------------

-- Inline table function
-- Directly defines the structure of the table to be returned using RETURNS TABLE
CREATE FUNCTION FN_ACTIVECUSTOMERS()
RETURNS TABLE
AS
RETURN (
	SELECT CUS.CUSTOMERID,
	       CUS.FIRSTNAME,
		   CUS.LASTNAME,
		   CUS.EMAIL,
		   ORD.ORDERID,
		   ORD.ORDERDATE,
		   ORD.TOTALAMOUNT
	FROM   CUSTOMERS AS CUS
	INNER JOIN ORDERS AS ORD
	ON     CUS.CUSTOMERID = ORD.CUSTOMERID
	WHERE  ORD.ORDERDATE  > CAST(DATEADD(MONTH, -6, GETDATE()) AS DATE)
);

-- Multistatemnet table function
-- Define la estructura de la tabla en una variable @VARIABLE_NAME utilizando RETURNS @VARIABLE_NAME
CREATE FUNCTION dbo.FN_ACTIVECUSTOMERS()
RETURNS @ACTIVECUSTOMERS TABLE (
    CUSTOMERID INT,
    FIRSTNAME VARCHAR(250),
    LASTNAME VARCHAR(250),
    EMAIL VARCHAR(300),
	ORDERID INT,
	ORDERDATE DATE,
    TOTALAMOUNT DECIMAL(20,2)
)
AS
BEGIN
    INSERT INTO @ActiveCustomers (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, ORDERID, ORDERDATE,TOTALAMOUNT)
    SELECT CUS.CUSTOMERID,
	       CUS.FIRSTNAME,
		   CUS.LASTNAME,
		   CUS.EMAIL,
		   ORD.ORDERID,
		   ORD.ORDERDATE,
		   ORD.TOTALAMOUNT
	FROM   CUSTOMERS AS CUS
	INNER JOIN ORDERS AS ORD
	ON     CUS.CUSTOMERID = ORD.CUSTOMERID
	WHERE  ORD.ORDERDATE  > CAST(DATEADD(MONTH, -6, GETDATE()) AS DATE);
    
    RETURN;
END;
