-----------------------------------------------------------
------------- SP_MONTHLYSALESREPORT PROCEDURE -------------
-----------------------------------------------------------

CREATE PROCEDURE SP_MONTHLYSALESREPORT (@STARTDATE DATE, @ENDDATE DATE)
AS
BEGIN
	SELECT YEAR(ORD.ORDERDATE) AS YEAR,
	       MONTH(ORD.ORDERDATE) AS MONTH,
		   ORDERDATE,
		   SUM(DET.QUANTITY) AS QUANTITY,
		   SUM(DET.QUANTITY * DET.UNITPRICE) AS TOTALAMOUNT
	FROM   ORDERDETAILS DET
	INNER JOIN ORDERS ORD
	ON     DET.ORDERID = ORD.ORDERID
	WHERE  ORDERDATE >= @STARTDATE
	AND    ORDERDATE <= @ENDDATE
	GROUP BY YEAR(ORD.ORDERDATE),
	       MONTH(ORD.ORDERDATE),
		   ORDERDATE
END;
