--------------------------------------------------
------------- VW_CUSTOMERORDERS VIEW -------------
--------------------------------------------------

CREATE VIEW VW_CUSTOMERORDERS AS
SELECT CUST.CUSTOMERID,
	   CUST.FIRSTNAME,
	   CUST.LASTNAME,
	   CUST.EMAIL,
	   COUNT(ORD.ORDERID) AS TOTALORDERS,
	   SUM(ORD.TOTALAMOUNT) AS TOTALAMOUNT,
	   YEAR(JOINDATE) AS YEAR
FROM   CUSTOMERS AS CUST
LEFT JOIN ORDERS AS ORD
ON CUST.CUSTOMERID = ORD.CUSTOMERID
WHERE  YEAR(JOINDATE) = 2023
GROUP BY CUST.CUSTOMERID,
	   CUST.FIRSTNAME,
	   CUST.LASTNAME,
	   CUST.EMAIL,
	   YEAR(JOINDATE)
;
