# Codigo SQL con los updates de los importes

update_details = """UPDATE ORDERDETAILS AS T1
SET    UNITPRICE = T2.PRICE
FROM   PRODUCTS AS T2
WHERE  T1.PRODUCTID = T2.PRODUCTID"""

update_orders = """UPDATE ORDERS AS ORD
SET TOTALAMOUNT = (
    SELECT SUM(DET.QUANTITY * DET.UNITPRICE)
    FROM ORDERDETAILS AS DET
    WHERE DET.ORDERID = ORD.ORDERID
)
WHERE EXISTS (
    SELECT 1
    FROM ORDERDETAILS AS DET
    WHERE DET.ORDERID = ORD.ORDERID
)"""
